apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: myapp
  name: myapp
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: 'registry.cn-shanghai.aliyuncs.com/public-namespace/myapp:v1'
          name: myapp
          ports:
            - containerPort: 80
