apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: myapp
  name: myapp
  namespace: devops
spec:
  ports:
    - nodePort: 32060
      port: 80
      targetPort: 80
  selector:
    app: myapp
  type: NodePort
